In [1]:
import numpy as np


# Task 1: Create a 3x3 Matrix of Random Integers between 1 and 50


---



In [2]:
# Task 1: Create a 3x3 Matrix of Random Integers between 1 and 50
without_seed_matrix = np.random.randint(1, 51, (3, 3))
print("Random 3x3 Matrix Without Seed:")
print(without_seed_matrix)



Random 3x3 Matrix Without Seed:
[[36 29 22]
 [33 40 12]
 [44 10  5]]


# Task 2: Create a 3x3 Matrix of Random Integers between 1 and 50 With a fixed seed

---




In [3]:
# Task 2: Create a 3x3 Matrix with a Fixed Seed
np.random.seed(10)
with_seed_matrix = np.random.randint(1, 51, (3, 3))
print("\nMatrix with Fixed Seed :")
print(with_seed_matrix)


Matrix with Fixed Seed :
[[10 37 16]
 [ 1 50 29]
 [26 30 49]]


# Task 3: Create a 3x3 Matrix of Random Integers between 1 and 50 Without a fixed seed


---



In [4]:
# Task 3: Another Random 3x3 Matrix Without Seed
without_seed_matrix_2 = np.random.randint(1, 51, (3, 3))
print("\nAnother Matrix Without Seed (Changes Each Run):")
print(without_seed_matrix_2)




Another Matrix Without Seed (Changes Each Run):
[[30 50  9]
 [10  1 43]
 [41 37 17]]


# Explanation:


---



- **Task 1:** Generates a random 3x3 matrix without setting a seed. As a result, the output will differ every time the script is run. This is called a non-deterministic process, meaning the results are unpredictable and unique on each execution.

  

- **Task 2:** Uses a fixed random seed (10 in this case). By setting the seed, the random number generation becomes deterministic. This means that the same sequence of random numbers (and hence the same matrix) will be produced every time the script runs, ensuring reproducibility.



- **Task 3:** Similar to Task 1, it generates another random matrix without a seed, leading to different values with every execution. However, it’s a fresh random matrix generated independently from Task 1.

  

# Key Differences:


---



- The main difference between Task 1 & 3 (without seed) and Task 2 (with seed) is that Task 2 provides repeatable results due to the fixed seed, while the other two will give different results with every script run.
